version: "3.9"

services:
  app:
    build: .
    container_name: meu_node_app
    ports:
      - "3000:3000"
    env_file:
      - .env
    volumes:
      - .:/app
      - /app/node_modules  # Evita conflito com node_modules da máquina
    restart: unless-stopped
